# Generated by Django 3.1.1 on 2022-06-30 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Price')),
                ('response', models.TextField(blank=True, default='{}', verbose_name='Response')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
