# Generated by Django 3.1.1 on 2022-06-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BitcoinPrice',
            new_name='Bitcoin',
        ),
    ]
