# Generated by Django 3.1.1 on 2022-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220630_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='symbol',
            field=models.CharField(default='BTCUSDT', max_length=100, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
