# Generated by Django 3.1.1 on 2022-06-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220630_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoin',
            name='response',
        ),
    ]
